### ISSUE TITLE
Couldn't get the demo to work

### ISSUE THREAD

**Issue by jmugan** [teaspn/teaspn-sdk#1]
I'm new to Visual Studio Code, but I set the Python to `.pyenv`, but somehow, when I debug with `Launch Client` I get
```
Traceback (most recent call last):
  File "server/teaspn_server.py", line 8, in <module>
    from server.handler_impl_sample import TeaspnHandlerSample
  File "teaspn-sdk/server/handler_impl_sample.py", line 19
    self._diag_to_replacements: Dict[Diagnostic, List[str]] = {}
                              ^
SyntaxError: invalid syntax
[Error - 9:16:54 PM] Connection to server got closed. Server will not be restarted.
```
It's almost like it is trying to use Python 2.

**Comment by mhagiwara** [comment]
It does look like it's using Python 2. What do you get if you simply run `python` under the root of your project directory?

**Comment by jmugan** [comment]
If I do `which python` I get `teaspn-sdk/.pyenv/bin/python` and it is Python 3. I have Anaconda installed. Maybe that is messing with something. 

Is there another way to test it without using Visual Studio Code. Maybe something from the command line?

**Comment by mhagiwara** [comment]
There's no way to test it from the command line, but it does sound like a good idea. Let me follow up on this—we are currently a bit busy getting ready for the EMNLP 2019 demo and cannot guarantee when this is addressed, though. Thank you for reporting anyways.
